// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGyhiyI99cDuLhBzjAuxNTWgi1-ZxvFgU',
    appId: '1:741726649881:web:16fb827e0b258f866cf488',
    messagingSenderId: '741726649881',
    projectId: 'money-mapping-backend',
    authDomain: 'money-mapping-backend.firebaseapp.com',
    storageBucket: 'money-mapping-backend.firebasestorage.app',
    measurementId: 'G-8R1X0RHT55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQzbQeSVjsUQX_DrQ8sAFrxDuRuEXee0',
    appId: '1:741726649881:android:a41ee66500e7274b6cf488',
    messagingSenderId: '741726649881',
    projectId: 'money-mapping-backend',
    storageBucket: 'money-mapping-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEnpuAVHDAIIy8SKGDxfne9nxfL7N0-8E',
    appId: '1:741726649881:ios:72becb6b7e478c8e6cf488',
    messagingSenderId: '741726649881',
    projectId: 'money-mapping-backend',
    storageBucket: 'money-mapping-backend.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEnpuAVHDAIIy8SKGDxfne9nxfL7N0-8E',
    appId: '1:741726649881:ios:72becb6b7e478c8e6cf488',
    messagingSenderId: '741726649881',
    projectId: 'money-mapping-backend',
    storageBucket: 'money-mapping-backend.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGyhiyI99cDuLhBzjAuxNTWgi1-ZxvFgU',
    appId: '1:741726649881:web:ce464bb757f18cb06cf488',
    messagingSenderId: '741726649881',
    projectId: 'money-mapping-backend',
    authDomain: 'money-mapping-backend.firebaseapp.com',
    storageBucket: 'money-mapping-backend.firebasestorage.app',
    measurementId: 'G-KDKQVVSGDN',
  );
}
